create table if not exists employment_type
(
    id          serial primary key                                         not null,
    name        varchar(25) check (length(name) between 1 and 25)          not null,
    description varchar(300) check (length(description) between 1 and 300) not null
);

insert into employment_type (name, description)
values ('B2B', 'Business-to-business is a situation where one business makes a commercial transaction with another.'),
       ('PERMANENT',
        'Permanent employment is a long-term employment arrangement where an individual is hired without a predetermined end date, typically providing job security, benefits, and a stable income.'),
       ('MANDATE',
        'A mandate contract is a legal agreement in which an individual (the mandatary) agrees to perform a specific task or service on behalf of another party (the mandator), usually for a specified period or until the task is completed.'),
       ('SPECIFIC_TASK',
        'A specific task contract is an employment agreement where an individual is hired to complete a defined task or project. The contract ends once the task is completed.'),
       ('INTERNSHIP',
        'An internship is a temporary position, often held by students or recent graduates, that provides practical experience in a particular field or profession, typically lasting for a fixed period and often with the possibility of leading to permanent employment.');

create table if not exists type_of_work
(
    id          serial primary key                                          not null,
    name        varchar(25) check ( length(name) between 1 and 25)          not null,
    description varchar(255) check ( length(description) between 1 and 255) not null
);

insert into type_of_work (name, description)
values ('FULL_TIME',
        'An employment in which workers work a minimum number of hours defined as such by their employer.'),
       ('PART_TIME', 'A form of employment that carries fewer hours per week than a full-time job.'),
       ('INTERNSHIP',
        'An internship is a temporary position within a company or organization, usually for a fixed period, where individuals, often students or recent graduates, gain practical experience and exposure to a particular industry or field.'),
       ('FREELANCE',
        'A form of self-employment where individuals offer their skills or services to clients or businesses on a temporary or project basis, working independently and without long-term employment commitments.');

create table if not exists experience_level
(
    id          serial primary key                                         not null,
    level       varchar(25) check (length(level) between 1 and 25)         not null,
    description varchar(300) check (length(description) between 1 and 300) not null
);

insert into experience_level (level, description)
values ('JUNIOR', 'Entry-level position typically held by individuals with limited experience or fresh graduates.'),
       ('MID', 'Intermediate level position requiring moderate experience and skill.'),
       ('SENIOR', 'Advanced level position typically held by experienced professionals with significant expertise.'),
       ('LEAD', 'Leadership or managerial level position responsible for guiding and overseeing projects or teams.');

create table if not exists operating_mode
(
    id          serial primary key                                         not null,
    name        varchar(25) check (length(name) between 1 and 25)          not null,
    description varchar(255) check (length(description) between 1 and 255) not null
);

insert into operating_mode (name, description)
values ('REMOTE',
        'Employees work entirely from a location other than the office, often from home or another remote location.'),
       ('HYBRID',
        'Combination of remote and office work, where employees have the flexibility to work from both home and the office, typically on scheduled days.'),
       ('OFFICE', 'Employees work primarily from the office location, adhering to a traditional in-office work setup.');

create table if not exists main_technology
(
    id   serial primary key                                not null,
    name varchar(30) check (length(name) between 1 and 30) not null
);

insert into main_technology (name)
values ('JS'),
       ('HTML'),
       ('PHP'),
       ('RUBY'),
       ('PYTHON'),
       ('JAVA'),
       ('.NET'),
       ('SCALA'),
       ('C'),
       ('MOBILE'),
       ('TESTING'),
       ('DEVOPS'),
       ('ADMIN'),
       ('UXUI'),
       ('PM'),
       ('GAME'),
       ('ANALYTICS'),
       ('SECURITY'),
       ('DATA'),
       ('GO'),
       ('SUPPORT'),
       ('ERP'),
       ('ARCHITECTURE');

create table if not exists currency
(
    id   serial primary key                                not null,
    name varchar(50) check (length(name) between 1 and 50) not null
);

insert into currency (name)
values ('PLN'),
       ('EUR'),
       ('USD'),
       ('GBP');

create table if not exists contact
(
    id      serial primary key                                   not null,
    name    varchar(50) check (length(name) between 3 and 50)    not null,
    surname varchar(50) check (length(surname) between 3 and 50) not null,
    email   varchar(100) check (length(email) between 3 and 100) not null,
    phone   varchar(25) check (length(phone) between 12 and 25)  not null
);

create table if not exists job_offer
(
    id                  serial primary key                                           not null,
    title               varchar(100) check (length(title) between 1 and 100)         not null,
    company_name        varchar(20) check (length(company_name) between 1 and 100)   not null,
    city                varchar(50) check (length(city) between 1 and 50)            not null,
    street              varchar(50) check (length(street) between 1 and 50)          not null,
    description         varchar(4400) check (length(description) between 1 and 4400) not null,
    remote_interview    boolean                                                      not null,
    main_technology_id  int                                                          not null,
    experience_level_id int                                                          not null,
    type_of_work_id     int                                                          not null,
    contact_id          int                                                          not null,
    apply_url           varchar(255),
    created_date        timestamp(6)                                                 not null,
    last_modified_date  timestamp(6)                                                 not null,
    constraint fk_main_technology foreign key (main_technology_id) references main_technology (id),
    constraint fk_experience_level foreign key (experience_level_id) references experience_level (id),
    constraint fk_type_of_work foreign key (type_of_work_id) references type_of_work (id),
    constraint fk_contact foreign key (contact_id) references contact (id)
);

create table if not exists offer_operating_mode
(
    id                serial primary key not null,
    job_offer_id      int,
    operating_mode_id int                not null,
    constraint fk_job_offer foreign key (job_offer_id) references job_offer (id)
);

create table if not exists employment
(
    id                 serial primary key not null,
    salary_from        int,
    salary_to          int,
    employment_type_id int                not null,
    currency_id        int                not null,
    job_offer_id       int,
    constraint fk_employment_type foreign key (employment_type_id) references employment_type (id),
    constraint fk_currency foreign key (currency_id) references currency (id),
    constraint fk_job_offer foreign key (job_offer_id) references job_offer (id)
);

create table if not exists skill
(
    id   serial primary key                                not null,
    name varchar(40) check (length(name) between 1 and 40) not null
);

insert into skill (name)
values ('.NET'),
       ('.NET_4.5'),
       ('.NET_C#'),
       ('.NET_CORE'),
       ('.NET_FRAMEWORK'),
       ('.NET_MVC'),
       ('3D'),
       ('ABAP'),
       ('ACTIVE_DIRECTORY'),
       ('ACTIVEMQ'),
       ('ADOBE_CC'),
       ('ADOBE_CREATIVE_SUITE'),
       ('ADOBE_PHOTOSHOP'),
       ('ADOBE_XD'),
       ('AGILE'),
       ('AI'),
       ('AIRFLOW'),
       ('AJAX'),
       ('AKKA'),
       ('ALGORITHMS'),
       ('AMAZON_AWS'),
       ('AMAZON_WEB_SERVICES'),
       ('ANALITYCZNE_MYŚLENIE'),
       ('ANALIZA_BIZNESOWA'),
       ('ANALYTICAL_THINKING'),
       ('ANALYTICS'),
       ('ANDROID'),
       ('ANDROID_SDK'),
       ('ANDROID_STUDIO'),
       ('ANGULAR'),
       ('ANGULAR_2'),
       ('ANGULAR_2+'),
       ('ANGULAR_4'),
       ('ANGULAR_4+'),
       ('ANGULAR_5'),
       ('ANGULAR_5+'),
       ('ANGULAR_6'),
       ('ANGULAR_7'),
       ('ANGULAR_MATERIAL'),
       ('ANGULARJS'),
       ('ANSIBLE'),
       ('APACHE'),
       ('APACHE_CORDOVA'),
       ('APACHE_HADOOP'),
       ('APACHE_JMETER'),
       ('APACHE_KAFKA'),
       ('APACHE_SPARK'),
       ('APACHE_TOMCAT'),
       ('APEX'),
       ('API'),
       ('API_TESTING'),
       ('APPIUM'),
       ('AR'),
       ('ARCHITECTURE'),
       ('ARM'),
       ('ARTIFACTORY'),
       ('AS400'),
       ('ASP.NET'),
       ('ASP.NET_CORE'),
       ('ASP.NET_MVC'),
       ('ASP.NET_WEB_API'),
       ('ASYNC_PROGRAMMING'),
       ('ASYNCIO'),
       ('ATLASSIAN'),
       ('AUTO_LAYOUT'),
       ('AUTOMATED_TESTING'),
       ('AUTOMATION_TOOLS'),
       ('AUTOMOTIVE'),
       ('AUTOSAR'),
       ('AWS'),
       ('AXURE_RP'),
       ('AZURE'),
       ('AZURE_DEVOPS'),
       ('AZURE_SERVICES'),
       ('BABEL'),
       ('BACKBONE.JS'),
       ('BACKEND'),
       ('BAMBOO'),
       ('BASH'),
       ('BAZY_DANYCH'),
       ('BDD'),
       ('BEHAT'),
       ('BEM'),
       ('BI'),
       ('BIG_DATA'),
       ('BIGQUERY'),
       ('BITBUCKET'),
       ('BLOCKCHAIN'),
       ('BOOST'),
       ('BOOTSTRAP'),
       ('BOOTSTRAP_3'),
       ('BOOTSTRAP_4'),
       ('BPM'),
       ('BPMN'),
       ('BPMN2'),
       ('BUSINESS_ANALYSIS'),
       ('BUSINESS_INTELLIGENCE'),
       ('C'),
       ('C#'),
       ('C++'),
       ('C++_14'),
       ('C++11'),
       ('CANVAS'),
       ('CASSANDRA'),
       ('CCNA'),
       ('CD'),
       ('CELERY'),
       ('CENTOS'),
       ('CHAI'),
       ('CHEF'),
       ('CI'),
       ('CI/CD'),
       ('CISCO'),
       ('CLEAN_CODE'),
       ('CLOJURE'),
       ('CLOUD'),
       ('CLOUD_COMPUTING'),
       ('CMAKE'),
       ('CMS'),
       ('COCOA'),
       ('COCOA_TOUCH'),
       ('COCOAPODS'),
       ('CODE_REVIEW'),
       ('CODEIGNITER'),
       ('COMMUNICATION'),
       ('COMMUNICATION_SKILLS'),
       ('COMPOSER'),
       ('COMPUTER_VISION'),
       ('CONFLUENCE'),
       ('CONSUL'),
       ('CONTACT_WITH_A_CLIENT'),
       ('CONTAINERS'),
       ('CONTINUOUS_INTEGRATION'),
       ('CONTINUOUS_DELIVERY'),
       ('CORE_DATA'),
       ('COREDATA'),
       ('CQRS'),
       ('CRM'),
       ('CSS'),
       ('CSS_3'),
       ('CSS_PREPROCESSORS'),
       ('CSS3'),
       ('CUCUMBER'),
       ('CUSTOMER_SUPPORT'),
       ('CYBERSECURITY'),
       ('CYPRESS'),
       ('DAGGER'),
       ('DAGGER_2'),
       ('DART'),
       ('DATA'),
       ('DATA_INTEGRATION'),
       ('DATA_MODELING'),
       ('DATA_SCIENCE'),
       ('DATA_WAREHOUSING'),
       ('DATABASES'),
       ('DATABRICKS'),
       ('DAX'),
       ('DB2'),
       ('DDD'),
       ('DEBIAN'),
       ('DEEP_LEARNING'),
       ('DEFINING_REQUIREMENTS'),
       ('DELPHI'),
       ('DESIGN_PATTERNS'),
       ('DESIGN_THINKING'),
       ('DEVEXPRESS'),
       ('DEVOPS'),
       ('DEVOPS_TOOLS'),
       ('DHCP'),
       ('DISTRIBUTED_SYSTEMS'),
       ('DJANGO'),
       ('DJANGO_REST_FRAMEWORK'),
       ('DNS'),
       ('DOCKER'),
       ('DOCTRINE'),
       ('DOCTRINE_2'),
       ('DOMAIN-DRIVEN_DESIGN'),
       ('DRUPAL'),
       ('DSP'),
       ('DWH'),
       ('E-COMMERCE'),
       ('ECLIPSE'),
       ('ECMASCRIPT'),
       ('ECMASCRIPT_6'),
       ('EF'),
       ('EJB'),
       ('ELASTIC'),
       ('ELASTICSEARCH'),
       ('ELIXIR'),
       ('ELK'),
       ('ELK_STACK'),
       ('EMBEDDED'),
       ('EMBEDDED_C'),
       ('EMBEDDED_SYSTEMS'),
       ('EMBER'),
       ('EMBER.JS'),
       ('ENGLISH'),
       ('ENTERPRISE'),
       ('ENTERPRISE_ARCHITECT'),
       ('ENTITY'),
       ('ENTITY_FRAMEWORK'),
       ('ERP'),
       ('ES_2015+'),
       ('ES6'),
       ('ES6+'),
       ('ES6+_SYNTAX'),
       ('ES7'),
       ('ESB'),
       ('ESPRESSO'),
       ('ETHEREUM'),
       ('ETL'),
       ('ETL_TOOLS'),
       ('EVENT_SOURCING'),
       ('EVENT_STORMING'),
       ('EVENT_STREAMING'),
       ('EVENT-DRIVEN_ARCHITECTURE'),
       ('EVENTSTORE'),
       ('EXCEL'),
       ('EXPRESS.JS'),
       ('EXT_JS'),
       ('FACEBOOK_API'),
       ('FASTLANE'),
       ('FIGMA'),
       ('FIREBASE'),
       ('FIREWALL'),
       ('FLASK'),
       ('FLINK'),
       ('FLOW'),
       ('FLUTTER'),
       ('FRENCH'),
       ('FRONT-END'),
       ('FRP'),
       ('FUNCTIONAL_PROGRAMMING'),
       ('FUNCTIONAL_TESTING'),
       ('GATLING'),
       ('GCP'),
       ('GERMAN'),
       ('GERRIT'),
       ('GHERKIN'),
       ('GIT'),
       ('GITFLOW'),
       ('GITHUB'),
       ('GITLAB'),
       ('GO'),
       ('GOLANG'),
       ('GOOGLE_ANALYTICS'),
       ('GOOGLE_CLOUD'),
       ('GOOGLE_CLOUD_PLATFORM'),
       ('GOOGLE_MAPS_API'),
       ('GOOGLE_PLAY'),
       ('GRADLE'),
       ('GRAFANA'),
       ('GRAILS'),
       ('GRAPHQL'),
       ('GROOVY'),
       ('GRPC'),
       ('GRUNT'),
       ('GUI'),
       ('GULP'),
       ('GULP.JS'),
       ('GWT'),
       ('HA'),
       ('HADOOP'),
       ('HAML'),
       ('HAPROXY'),
       ('HARDWARE'),
       ('HASKELL'),
       ('HBASE'),
       ('HELPDESK'),
       ('HEROKU'),
       ('HIBERNATE'),
       ('HIVE'),
       ('HP_ALM'),
       ('HTML'),
       ('HTML5'),
       ('HTML5_/_CSS3'),
       ('HTTP'),
       ('HTTP_PROTOCOL'),
       ('HTTPS'),
       ('HYBRIS'),
       ('HYPER-V'),
       ('IAC'),
       ('IBM'),
       ('IIS'),
       ('ILLUSTRATOR'),
       ('IMAGE_PROCESSING'),
       ('INDESIGN'),
       ('INFLUXDB'),
       ('INFORMATICA'),
       ('INFORMATICA_POWERCENTER'),
       ('INFORMATION_SECURITY'),
       ('INTEGRATION'),
       ('INTELLIJ'),
       ('INVISION'),
       ('IONIC'),
       ('IOS'),
       ('IOS_FRAMEWORKS'),
       ('IOS_SDK'),
       ('IOT'),
       ('IP'),
       ('IP_NETWORKS'),
       ('ISTQB'),
       ('ISTQB_FOUNDATION'),
       ('IT'),
       ('IT_SECURITY'),
       ('IT_SUPPORT'),
       ('ITIL'),
       ('J2EE'),
       ('JASMINE'),
       ('JAVA'),
       ('JAVA_11'),
       ('JAVA_8'),
       ('JAVA_8+'),
       ('JAVA_EE'),
       ('JAVA_SE'),
       ('JAVASCRIPT'),
       ('JAVASCRIPT_(JQUERY)'),
       ('JAVASCRIPT_FRAMEWORK'),
       ('JBEHAVE'),
       ('JBOSS'),
       ('JDBC'),
       ('JEE'),
       ('JENKINS'),
       ('JEST'),
       ('JETTY'),
       ('JIRA'),
       ('JMETER'),
       ('JMS'),
       ('JPA'),
       ('JQUERY'),
       ('JS'),
       ('JS_ES6'),
       ('JS_FRAMEWORKS'),
       ('JSF'),
       ('JSON'),
       ('JSP'),
       ('JUNIT'),
       ('JVM'),
       ('KAFKA'),
       ('KANBAN'),
       ('KARMA'),
       ('KERAS'),
       ('KEYCLOAK'),
       ('KIBANA'),
       ('KNOCKOUT'),
       ('KOTLIN'),
       ('KUBERNETES'),
       ('KVM'),
       ('LAN'),
       ('LARAVEL'),
       ('LARAVEL_MIX'),
       ('LEADERSHIP'),
       ('LEAN'),
       ('LESS'),
       ('LIGHTNING'),
       ('LINQ'),
       ('LINUX'),
       ('LINUX_(DEBIAN)'),
       ('LINUX_/_UNIX'),
       ('LINUX_KERNEL'),
       ('LINUX_NETWORKING'),
       ('LINUX_OS'),
       ('LOADRUNNER'),
       ('MAC_OS'),
       ('MACHINE_LEARNING'),
       ('MAGENTO'),
       ('MAGENTO_2'),
       ('MANAGEMENT'),
       ('MANUAL_TESTING'),
       ('MARIADB'),
       ('MATERIAL_DESIGN'),
       ('MATLAB'),
       ('MAVEN'),
       ('MEMCACHED'),
       ('MERCURIAL'),
       ('MESOS'),
       ('MICROSERVICE_ARCHITECTURE'),
       ('MICROSERVICES'),
       ('MICROSOFT'),
       ('MICROSOFT_365'),
       ('MICROSOFT_AZURE'),
       ('MICROSOFT_AZURE_CLOUD'),
       ('MICROSOFT_OFFICE'),
       ('MICROSOFT_SQL'),
       ('MICROSOFT_VISUAL_STUDIO'),
       ('MICROSOFT_WINDOWS'),
       ('MOBILE'),
       ('MOBILE_APP_TESTING'),
       ('MOBILE_APPS'),
       ('MOBILE_DEVELOPMENT'),
       ('MOBX'),
       ('MOCHA'),
       ('MOCKITO'),
       ('MONGODB'),
       ('MONITORING_SYSTEMS'),
       ('MONITORING_TOOLS'),
       ('MQ'),
       ('MS_AZURE'),
       ('MS_EXCEL'),
       ('MS_EXCHANGE'),
       ('MS_OFFICE'),
       ('MS_PROJECT'),
       ('MS_SQL'),
       ('MS_SQL_SERVER'),
       ('MSSQL'),
       ('MULE'),
       ('MULESOFT'),
       ('MULTI_BROWSER_TESTING'),
       ('MVC'),
       ('MVC_FRAMEWORKS'),
       ('MVC_PATTERN'),
       ('MVP'),
       ('MVVM'),
       ('MYSQL'),
       ('NAGIOS'),
       ('NEST.JS'),
       ('NESTJS'),
       ('NETWORK'),
       ('NETWORK_ADMINISTRATION'),
       ('NETWORK_PROTOCOLS'),
       ('NETWORKING'),
       ('NETWORKS'),
       ('NEXT.JS'),
       ('NGINX'),
       ('NGNIX'),
       ('NGRX'),
       ('NHIBERNATE'),
       ('NIEMIECKI'),
       ('NLP'),
       ('NODE'),
       ('NODE.JS'),
       ('NODE.JS_EXPRESS'),
       ('NODEJS'),
       ('NOSQL'),
       ('NPM'),
       ('NUMPY'),
       ('NUNIT'),
       ('OBJECTIVE-C'),
       ('OCTOPUS'),
       ('OFFICE_365'),
       ('OFFLINE_STORAGE'),
       ('OLAP'),
       ('OOD'),
       ('OOP'),
       ('OPEN_SOURCE'),
       ('OPENCV'),
       ('OPENGL'),
       ('OPENSHIFT'),
       ('OPENSTACK'),
       ('ORACLE'),
       ('ORACLE_DB'),
       ('ORACLE_SQL'),
       ('ORACLE_WEBLOGIC'),
       ('ORM'),
       ('OS_X_LINUX'),
       ('OWASP'),
       ('PANDAS'),
       ('PENTAHO'),
       ('PEOPLE_MANAGEMENT'),
       ('PERL'),
       ('PHOTOSHOP'),
       ('PHP'),
       ('PHP_5'),
       ('PHP_5.4'),
       ('PHP_7'),
       ('PHP_7.X'),
       ('PHP_8'),
       ('PHPUNIT'),
       ('PL/SQL'),
       ('PLAYWRIGHT'),
       ('PM'),
       ('POLISH'),
       ('POSTGRESQL'),
       ('POSTMAN'),
       ('POSTRESQL'),
       ('POWER_BI'),
       ('POWERSHELL'),
       ('PRESTASHOP'),
       ('PRINCE2'),
       ('PROACTIVITY'),
       ('PROBLEM_SOLVING'),
       ('PRODUCT_MANAGEMENT'),
       ('PROGRAMMING'),
       ('PROJECT_MANAGEMENT'),
       ('PROMETHEUS'),
       ('PROTOTYPING'),
       ('PROTRACTOR'),
       ('PUPPET'),
       ('PUSH_NOTIFICATIONS'),
       ('PWA'),
       ('PYQT'),
       ('PYSPARK'),
       ('PYTEST'),
       ('PYTHON'),
       ('PYTHON_3'),
       ('PYTHON_3.X'),
       ('PYTORCH'),
       ('QA'),
       ('QT'),
       ('QUALITY_ASSURANCE'),
       ('R'),
       ('RABBITMQ'),
       ('RAILS'),
       ('RAZOR'),
       ('RDBMS'),
       ('REACT'),
       ('REACT_NATIVE'),
       ('REACTIVE_PROGRAMMING'),
       ('REACTJS'),
       ('REALM'),
       ('REASON'),
       ('RED_HAT'),
       ('REDIS'),
       ('REDMINE'),
       ('REDUX'),
       ('RELACYJNE_BAZY_DANYCH'),
       ('RELATIONAL_DATABASES'),
       ('RESPONSIVE_WEB_DESIGN'),
       ('REST'),
       ('REST_API'),
       ('REST_SERVICES'),
       ('RESTFUL'),
       ('RESTFUL_API'),
       ('RETROFIT'),
       ('RISK_MANAGEMENT'),
       ('ROBOT_FRAMEWORK'),
       ('ROUTING'),
       ('RPA'),
       ('RPG'),
       ('RSPEC'),
       ('RTOS'),
       ('RUBY'),
       ('RUBY_ON_RAILS'),
       ('RUST'),
       ('RWD'),
       ('RXJAVA'),
       ('RXJAVA_2'),
       ('RXJS'),
       ('RXKOTLIN'),
       ('RXSWIFT'),
       ('SAAS'),
       ('SALES'),
       ('SALESFORCE'),
       ('SAP'),
       ('SAP_BO'),
       ('SAP_HANA'),
       ('SAP_MM'),
       ('SAP_SD'),
       ('SAS'),
       ('SASS'),
       ('SASS_(BEM)'),
       ('SCALA'),
       ('SCRAPY'),
       ('SCRIPTING'),
       ('SCRUM'),
       ('SCRUM_MASTER'),
       ('SCSS'),
       ('SDLC'),
       ('SECURITY'),
       ('SELENIUM'),
       ('SELENIUM_WEBDRIVER'),
       ('SEO'),
       ('SERVERLESS'),
       ('SERVICENOW'),
       ('SHAREPOINT'),
       ('SHELL'),
       ('SHELL_SCRIPTING'),
       ('SHOPIFY'),
       ('SIEM'),
       ('SIP'),
       ('SKETCH'),
       ('SLACK'),
       ('SNOWFLAKE'),
       ('SOA'),
       ('SOAP'),
       ('SOAPUI'),
       ('SOCIAL_MEDIA'),
       ('SOCKET.IO'),
       ('SOFTWARE_ARCHITECTURE'),
       ('SOFTWARE_DEVELOPMENT'),
       ('SOLID'),
       ('SOLID_PRINCIPLES'),
       ('SOLIDITY'),
       ('SOLR'),
       ('SONAR'),
       ('SONARQUBE'),
       ('SPA'),
       ('SPARK'),
       ('SPLUNK'),
       ('SPOCK'),
       ('SPRING'),
       ('SPRING_5'),
       ('SPRING_BOOT'),
       ('SPRING_CLOUD'),
       ('SPRING_MVC'),
       ('SQL'),
       ('SQL_SERVER'),
       ('SQLALCHEMY'),
       ('SQLITE'),
       ('SSAS'),
       ('SSIS'),
       ('SSRS'),
       ('STATISTICS'),
       ('STL'),
       ('SVG'),
       ('SVN'),
       ('SWAGGER'),
       ('SWIFT'),
       ('SWIFTUI'),
       ('SWING'),
       ('SYMFONY'),
       ('SYMFONY_2'),
       ('SYMFONY_3'),
       ('SYMFONY_4'),
       ('SYMPHONY'),
       ('T-SQL'),
       ('TABLEAU'),
       ('TABULAR'),
       ('TCP'),
       ('TCP/IP'),
       ('TDD'),
       ('TEAM_LEADERSHIP'),
       ('TEAM_MANAGEMENT'),
       ('TEAM_PLAYER'),
       ('TEAMCITY'),
       ('TEAMWORK'),
       ('TELCO'),
       ('TENSORFLOW'),
       ('TERADATA'),
       ('TERRAFORM'),
       ('TEST_AUTOMATION'),
       ('TEST_CASES'),
       ('TEST_PLANNING'),
       ('TEST_SCENARIOS'),
       ('TESTING'),
       ('TESTING_MOBILE_APPS'),
       ('TESTING_TOOLS'),
       ('TESTLINK'),
       ('TESTRAIL'),
       ('TESTY_FUNKCJONALNE'),
       ('TFS'),
       ('TOGAF'),
       ('TOMCAT'),
       ('TORNADO'),
       ('TROUBLESHOOTING'),
       ('TWIG'),
       ('TYPESCRIPT'),
       ('UBUNTU'),
       ('UI'),
       ('UI_DESIGN'),
       ('UIKIT'),
       ('UIPATH'),
       ('UML'),
       ('UNIT_TESTING'),
       ('UNITY'),
       ('UNITY_3D'),
       ('UNIX'),
       ('UNREAL_ENGINE'),
       ('UNREAL_ENGINE_4'),
       ('USABILITY_TESTING'),
       ('USER_INTERFACE'),
       ('USER_STORIES'),
       ('UX'),
       ('UX_DESIGN'),
       ('UX_RESEARCH'),
       ('UX/UI'),
       ('UXPIN'),
       ('VAADIN'),
       ('VAGRANT'),
       ('VARNISH'),
       ('VB.NET'),
       ('VBA'),
       ('VIRTUALIZATION'),
       ('VISUAL_BASIC'),
       ('VISUAL_STUDIO'),
       ('VMWARE'),
       ('VOIP'),
       ('VPN'),
       ('VUE'),
       ('VUE.JS'),
       ('WCF'),
       ('WEB_API'),
       ('WEB_APPLICATION_TESTING'),
       ('WEB_APPLICATIONS'),
       ('WEB_DEVELOPMENT'),
       ('WEB_SERVICES'),
       ('WEBCON'),
       ('WEBCON_BPS'),
       ('WEBDRIVER'),
       ('WEBGL'),
       ('WEBLOGIC'),
       ('WEBMETHODS'),
       ('WEBPACK'),
       ('WEBSERVICE'),
       ('WEBSOCKET'),
       ('WEBSPHERE'),
       ('WILDFLY'),
       ('WINDOWS'),
       ('WINDOWS_10'),
       ('WINDOWS_ADMINISTRATION'),
       ('WINDOWS_FORMS'),
       ('WINDOWS_SERVER'),
       ('WINFORMS'),
       ('WOOCOMMERCE'),
       ('WORDPRESS'),
       ('WPF'),
       ('WRITING_TEST_CASES'),
       ('WRITING_TEST_SCENARIOS'),
       ('XAMARIN'),
       ('XCODE'),
       ('XML'),
       ('XPATH'),
       ('XSD'),
       ('XSLT'),
       ('YARN'),
       ('YII'),
       ('ZABBIX'),
       ('ZEND'),
       ('ZEND_EXPRESSIVE'),
       ('ZEND_FRAMEWORK'),
       ('ZEPLIN'),
       ('ZMQ');

create table if not exists required_skill
(
    id           serial primary key                         not null,
    level        int check ( (level <= 5) and (level >= 1)) not null,
    job_offer_id int,
    skill_id     int                                        not null,
    constraint fk_job_offer foreign key (job_offer_id) references job_offer (id),
    constraint fk_skill foreign key (skill_id) references skill (id)
);