create table if not exists employment_type
(
    id          serial primary key                                         not null,
    name        varchar(25) check (length(name) between 1 and 25)          not null,
    description varchar(300) check (length(description) between 1 and 300) not null
);

insert into employment_type (name, description)
values ('B2B', 'Business-to-business is a situation where one business makes a commercial transaction with another.'),
       ('PERMANENT',
        'Permanent employment is a long-term employment arrangement where an individual is hired without a predetermined end date, typically providing job security, benefits, and a stable income.'),
       ('MANDATE',
        'A mandate contract is a legal agreement in which an individual (the mandatary) agrees to perform a specific task or service on behalf of another party (the mandator), usually for a specified period or until the task is completed.'),
       ('SPECIFIC TASK',
        'A specific task contract is an employment agreement where an individual is hired to complete a defined task or project. The contract ends once the task is completed.'),
       ('INTERNSHIP',
        'An internship is a temporary position, often held by students or recent graduates, that provides practical experience in a particular field or profession, typically lasting for a fixed period and often with the possibility of leading to permanent employment.');

create table if not exists type_of_work
(
    id          serial primary key                                          not null,
    name        varchar(25) check ( length(name) between 1 and 25)          not null,
    description varchar(255) check ( length(description) between 1 and 255) not null
);

insert into type_of_work (name, description)
values ('FULL TIME',
        'An employment in which workers work a minimum number of hours defined as such by their employer.'),
       ('PART TIME', 'A form of employment that carries fewer hours per week than a full-time job.'),
       ('INTERNSHIP',
        'An internship is a temporary position within a company or organization, usually for a fixed period, where individuals, often students or recent graduates, gain practical experience and exposure to a particular industry or field.'),
       ('FREELANCE',
        'A form of self-employment where individuals offer their skills or services to clients or businesses on a temporary or project basis, working independently and without long-term employment commitments.');

create table if not exists experience_level
(
    id          serial primary key                                         not null,
    level       varchar(25) check (length(level) between 1 and 25)         not null,
    description varchar(300) check (length(description) between 1 and 300) not null
);

insert into experience_level (level, description)
values ('JUNIOR', 'Entry-level position typically held by individuals with limited experience or fresh graduates.'),
       ('MID', 'Intermediate level position requiring moderate experience and skill.'),
       ('SENIOR', 'Advanced level position typically held by experienced professionals with significant expertise.'),
       ('LEAD', 'Leadership or managerial level position responsible for guiding and overseeing projects or teams.');

create table if not exists operating_mode
(
    id          serial primary key                                         not null,
    name        varchar(25) check (length(name) between 1 and 25)          not null,
    description varchar(255) check (length(description) between 1 and 255) not null
);

insert into operating_mode (name, description)
values ('REMOTE',
        'Employees work entirely from a location other than the office, often from home or another remote location.'),
       ('HYBRID',
        'Combination of remote and office work, where employees have the flexibility to work from both home and the office, typically on scheduled days.'),
       ('OFFICE', 'Employees work primarily from the office location, adhering to a traditional in-office work setup.');

create table if not exists main_technology
(
    id   serial primary key                                not null,
    name varchar(30) check (length(name) between 1 and 30) not null
);

insert into main_technology (name)
values ('JS'),
       ('HTML'),
       ('PHP'),
       ('RUBY'),
       ('PYTHON'),
       ('JAVA'),
       ('.NET'),
       ('SCALA'),
       ('C'),
       ('MOBILE'),
       ('TESTING'),
       ('DEVOPS'),
       ('ADMIN'),
       ('UXUI'),
       ('PM'),
       ('GAME'),
       ('ANALYTICS'),
       ('SECURITY'),
       ('DATA'),
       ('GO'),
       ('SUPPORT'),
       ('ERP'),
       ('ARCHITECTURE');

create table if not exists currency
(
    id   serial primary key                                not null,
    name varchar(50) check (length(name) between 1 and 50) not null
);

insert into currency (name)
values ('PLN'),
       ('EUR'),
       ('USD'),
       ('GBP');

create table if not exists contact
(
    id      serial primary key                                   not null,
    name    varchar(50) check (length(name) between 3 and 50)    not null,
    surname varchar(50) check (length(surname) between 3 and 50) not null,
    email   varchar(100) check (length(email) between 3 and 100) not null,
    phone   varchar(25) check (length(phone) between 12 and 25)  not null
);

create table if not exists job_offer
(
    id                  serial primary key                                           not null,
    title               varchar(100) check (length(title) between 1 and 100)         not null,
    company_name        varchar(20) check (length(company_name) between 1 and 100)   not null,
    city                varchar(50) check (length(city) between 1 and 50)            not null,
    street              varchar(50) check (length(street) between 1 and 50)          not null,
    description         varchar(4400) check (length(description) between 1 and 4400) not null,
    remote_interview    boolean                                                      not null,
    main_technology_id  int                                                          not null,
    experience_level_id int                                                          not null,
    type_of_work_id     int                                                          not null,
    contact_id          int                                                          not null,
    apply_url           varchar(255),
    created_date        timestamp(6)                                                 not null,
    last_modified_date  timestamp(6)                                                 not null,
    constraint fk_main_technology foreign key (main_technology_id) references main_technology (id),
    constraint fk_experience_level foreign key (experience_level_id) references experience_level (id),
    constraint fk_type_of_work foreign key (type_of_work_id) references type_of_work (id),
    constraint fk_contact foreign key (contact_id) references contact (id)
);

create table if not exists offer_operating_mode
(
    id                serial primary key not null,
    job_offer_id      int,
    operating_mode_id int                not null,
    constraint fk_job_offer foreign key (job_offer_id) references job_offer (id)
);

create table if not exists employment
(
    id                 serial primary key not null,
    salary_from        int,
    salary_to          int,
    employment_type_id int                not null,
    currency_id        int                not null,
    job_offer_id       int,
    constraint fk_employment_type foreign key (employment_type_id) references employment_type (id),
    constraint fk_currency foreign key (currency_id) references currency (id),
    constraint fk_job_offer foreign key (job_offer_id) references job_offer (id)
);

create table if not exists skill
(
    id   serial primary key                                not null,
    name varchar(40) check (length(name) between 1 and 40) not null
);

insert into skill (name)
values ('.NET'),
       ('.NET 4.5'),
       ('.NET C#'),
       ('.NET CORE'),
       ('.NET FRAMEWORK'),
       ('.NET MVC'),
       ('3D'),
       ('ABAP'),
       ('ACTIVE DIRECTORY'),
       ('ACTIVEMQ'),
       ('ADOBE CC'),
       ('ADOBE CREATIVE SUITE'),
       ('ADOBE PHOTOSHOP'),
       ('ADOBE XD'),
       ('AGILE'),
       ('AI'),
       ('AIRFLOW'),
       ('AJAX'),
       ('AKKA'),
       ('ALGORITHMS'),
       ('AMAZON AWS'),
       ('AMAZON WEB SERVICES'),
       ('ANALYTICAL THINKING'),
       ('ANALYTICS'),
       ('ANDROID'),
       ('ANDROID SDK'),
       ('ANDROID STUDIO'),
       ('ANGULAR'),
       ('ANGULAR 2'),
       ('ANGULAR 2+'),
       ('ANGULAR 4'),
       ('ANGULAR 4+'),
       ('ANGULAR 5'),
       ('ANGULAR 5+'),
       ('ANGULAR 6'),
       ('ANGULAR 7'),
       ('ANGULAR MATERIAL'),
       ('ANGULARJS'),
       ('ANSIBLE'),
       ('APACHE'),
       ('APACHE CORDOVA'),
       ('APACHE HADOOP'),
       ('APACHE JMETER'),
       ('APACHE KAFKA'),
       ('APACHE SPARK'),
       ('APACHE TOMCAT'),
       ('APEX'),
       ('API'),
       ('API TESTING'),
       ('APPIUM'),
       ('AR'),
       ('ARCHITECTURE'),
       ('ARM'),
       ('ARTIFACTORY'),
       ('AS400'),
       ('ASP.NET'),
       ('ASP.NET CORE'),
       ('ASP.NET MVC'),
       ('ASP.NET WEB API'),
       ('ASYNC PROGRAMMING'),
       ('ASYNCIO'),
       ('ATLASSIAN'),
       ('AUTO LAYOUT'),
       ('AUTOMATED TESTING'),
       ('AUTOMATION TOOLS'),
       ('AUTOMOTIVE'),
       ('AUTOSAR'),
       ('AWS'),
       ('AXURE RP'),
       ('AZURE'),
       ('AZURE DEVOPS'),
       ('AZURE SERVICES'),
       ('BABEL'),
       ('BACKBONE.JS'),
       ('BACKEND'),
       ('BAMBOO'),
       ('BASH'),
       ('BAZY DANYCH'),
       ('BDD'),
       ('BEHAT'),
       ('BEM'),
       ('BI'),
       ('BIG DATA'),
       ('BIGQUERY'),
       ('BITBUCKET'),
       ('BLOCKCHAIN'),
       ('BOOST'),
       ('BOOTSTRAP'),
       ('BOOTSTRAP 3'),
       ('BOOTSTRAP 4'),
       ('BPM'),
       ('BPMN'),
       ('BPMN2'),
       ('BUSINESS ANALYSIS'),
       ('BUSINESS INTELLIGENCE'),
       ('C'),
       ('C#'),
       ('C++'),
       ('C++ 14'),
       ('C++11'),
       ('CANVAS'),
       ('CASSANDRA'),
       ('CCNA'),
       ('CD'),
       ('CELERY'),
       ('CENTOS'),
       ('CHAI'),
       ('CHEF'),
       ('CI'),
       ('CI/CD'),
       ('CISCO'),
       ('CLEAN CODE'),
       ('CLOJURE'),
       ('CLOUD'),
       ('CLOUD COMPUTING'),
       ('CMAKE'),
       ('CMS'),
       ('COCOA'),
       ('COCOA TOUCH'),
       ('COCOAPODS'),
       ('CODE REVIEW'),
       ('CODEIGNITER'),
       ('COMMUNICATION'),
       ('COMMUNICATION SKILLS'),
       ('COMPOSER'),
       ('COMPUTER VISION'),
       ('CONFLUENCE'),
       ('CONSUL'),
       ('CONTACT WITH A CLIENT'),
       ('CONTAINERS'),
       ('CONTINUOUS INTEGRATION'),
       ('CONTINUOUS DELIVERY'),
       ('CORE DATA'),
       ('COREDATA'),
       ('CQRS'),
       ('CRM'),
       ('CSS'),
       ('CSS 3'),
       ('CSS PREPROCESSORS'),
       ('CSS3'),
       ('CUCUMBER'),
       ('CUSTOMER SUPPORT'),
       ('CYBERSECURITY'),
       ('CYPRESS'),
       ('DAGGER'),
       ('DAGGER 2'),
       ('DART'),
       ('DATA'),
       ('DATA INTEGRATION'),
       ('DATA MODELING'),
       ('DATA SCIENCE'),
       ('DATA WAREHOUSING'),
       ('DATABASES'),
       ('DATABRICKS'),
       ('DAX'),
       ('DB2'),
       ('DDD'),
       ('DEBIAN'),
       ('DEEP LEARNING'),
       ('DEFINING REQUIREMENTS'),
       ('DELPHI'),
       ('DESIGN PATTERNS'),
       ('DESIGN THINKING'),
       ('DEVEXPRESS'),
       ('DEVOPS'),
       ('DEVOPS TOOLS'),
       ('DHCP'),
       ('DISTRIBUTED SYSTEMS'),
       ('DJANGO'),
       ('DJANGO REST FRAMEWORK'),
       ('DNS'),
       ('DOCKER'),
       ('DOCTRINE'),
       ('DOCTRINE 2'),
       ('DOMAIN-DRIVEN DESIGN'),
       ('DRUPAL'),
       ('DSP'),
       ('DWH'),
       ('E-COMMERCE'),
       ('ECLIPSE'),
       ('ECMASCRIPT'),
       ('ECMASCRIPT 6'),
       ('EF'),
       ('EJB'),
       ('ELASTIC'),
       ('ELASTICSEARCH'),
       ('ELIXIR'),
       ('ELK'),
       ('ELK STACK'),
       ('EMBEDDED'),
       ('EMBEDDED C'),
       ('EMBEDDED SYSTEMS'),
       ('EMBER'),
       ('EMBER.JS'),
       ('ENGLISH'),
       ('ENTERPRISE'),
       ('ENTERPRISE ARCHITECT'),
       ('ENTITY'),
       ('ENTITY FRAMEWORK'),
       ('ERP'),
       ('ES 2015+'),
       ('ES6'),
       ('ES6+'),
       ('ES6+ SYNTAX'),
       ('ES7'),
       ('ESB'),
       ('ESPRESSO'),
       ('ETHEREUM'),
       ('ETL'),
       ('ETL TOOLS'),
       ('EVENT SOURCING'),
       ('EVENT STORMING'),
       ('EVENT STREAMING'),
       ('EVENT-DRIVEN ARCHITECTURE'),
       ('EVENTSTORE'),
       ('EXCEL'),
       ('EXPRESS.JS'),
       ('EXT JS'),
       ('FACEBOOK API'),
       ('FASTLANE'),
       ('FIGMA'),
       ('FIREBASE'),
       ('FIREWALL'),
       ('FLASK'),
       ('FLINK'),
       ('FLOW'),
       ('FLUTTER'),
       ('FRENCH'),
       ('FRONT-END'),
       ('FRP'),
       ('FUNCTIONAL PROGRAMMING'),
       ('FUNCTIONAL TESTING'),
       ('GATLING'),
       ('GCP'),
       ('GERMAN'),
       ('GERRIT'),
       ('GHERKIN'),
       ('GIT'),
       ('GITFLOW'),
       ('GITHUB'),
       ('GITLAB'),
       ('GO'),
       ('GOLANG'),
       ('GOOGLE ANALYTICS'),
       ('GOOGLE CLOUD'),
       ('GOOGLE CLOUD PLATFORM'),
       ('GOOGLE MAPS API'),
       ('GOOGLE PLAY'),
       ('GRADLE'),
       ('GRAFANA'),
       ('GRAILS'),
       ('GRAPHQL'),
       ('GROOVY'),
       ('GRPC'),
       ('GRUNT'),
       ('GUI'),
       ('GULP'),
       ('GULP.JS'),
       ('GWT'),
       ('HA'),
       ('HADOOP'),
       ('HAML'),
       ('HAPROXY'),
       ('HARDWARE'),
       ('HASKELL'),
       ('HBASE'),
       ('HELPDESK'),
       ('HEROKU'),
       ('HIBERNATE'),
       ('HIVE'),
       ('HP ALM'),
       ('HTML'),
       ('HTML5'),
       ('HTML5 / CSS3'),
       ('HTTP'),
       ('HTTP PROTOCOL'),
       ('HTTPS'),
       ('HYBRIS'),
       ('HYPER-V'),
       ('IAC'),
       ('IBM'),
       ('IIS'),
       ('ILLUSTRATOR'),
       ('IMAGE PROCESSING'),
       ('INDESIGN'),
       ('INFLUXDB'),
       ('INFORMATICA'),
       ('INFORMATICA POWERCENTER'),
       ('INFORMATION SECURITY'),
       ('INTEGRATION'),
       ('INTELLIJ'),
       ('INVISION'),
       ('IONIC'),
       ('IOS'),
       ('IOS FRAMEWORKS'),
       ('IOS SDK'),
       ('IOT'),
       ('IP'),
       ('IP NETWORKS'),
       ('ISTQB'),
       ('ISTQB FOUNDATION'),
       ('IT'),
       ('IT SECURITY'),
       ('IT SUPPORT'),
       ('ITIL'),
       ('J2EE'),
       ('JASMINE'),
       ('JAVA'),
       ('JAVA 11'),
       ('JAVA 8'),
       ('JAVA 8+'),
       ('JAVA EE'),
       ('JAVA SE'),
       ('JAVASCRIPT'),
       ('JAVASCRIPT (JQUERY)'),
       ('JAVASCRIPT FRAMEWORK'),
       ('JBEHAVE'),
       ('JBOSS'),
       ('JDBC'),
       ('JEE'),
       ('JENKINS'),
       ('JEST'),
       ('JETTY'),
       ('JIRA'),
       ('JMETER'),
       ('JMS'),
       ('JPA'),
       ('JQUERY'),
       ('JS'),
       ('JS ES6'),
       ('JS FRAMEWORKS'),
       ('JSF'),
       ('JSON'),
       ('JSP'),
       ('JUNIT'),
       ('JVM'),
       ('KAFKA'),
       ('KANBAN'),
       ('KARMA'),
       ('KERAS'),
       ('KEYCLOAK'),
       ('KIBANA'),
       ('KNOCKOUT'),
       ('KOTLIN'),
       ('KUBERNETES'),
       ('KVM'),
       ('LAN'),
       ('LARAVEL'),
       ('LARAVEL MIX'),
       ('LEADERSHIP'),
       ('LEAN'),
       ('LESS'),
       ('LIGHTNING'),
       ('LINQ'),
       ('LINUX'),
       ('LINUX (DEBIAN)'),
       ('LINUX / UNIX'),
       ('LINUX KERNEL'),
       ('LINUX NETWORKING'),
       ('LINUX OS'),
       ('LOADRUNNER'),
       ('MAC OS'),
       ('MACHINE LEARNING'),
       ('MAGENTO'),
       ('MAGENTO 2'),
       ('MANAGEMENT'),
       ('MANUAL TESTING'),
       ('MARIADB'),
       ('MATERIAL DESIGN'),
       ('MATLAB'),
       ('MAVEN'),
       ('MEMCACHED'),
       ('MERCURIAL'),
       ('MESOS'),
       ('MICROSERVICE ARCHITECTURE'),
       ('MICROSERVICES'),
       ('MICROSOFT'),
       ('MICROSOFT 365'),
       ('MICROSOFT AZURE'),
       ('MICROSOFT AZURE CLOUD'),
       ('MICROSOFT OFFICE'),
       ('MICROSOFT SQL'),
       ('MICROSOFT VISUAL STUDIO'),
       ('MICROSOFT WINDOWS'),
       ('MOBILE'),
       ('MOBILE APP TESTING'),
       ('MOBILE APPS'),
       ('MOBILE DEVELOPMENT'),
       ('MOBX'),
       ('MOCHA'),
       ('MOCKITO'),
       ('MONGODB'),
       ('MONITORING SYSTEMS'),
       ('MONITORING TOOLS'),
       ('MQ'),
       ('MS AZURE'),
       ('MS EXCEL'),
       ('MS EXCHANGE'),
       ('MS OFFICE'),
       ('MS PROJECT'),
       ('MS SQL'),
       ('MS SQL SERVER'),
       ('MSSQL'),
       ('MULE'),
       ('MULESOFT'),
       ('MULTI BROWSER TESTING'),
       ('MVC'),
       ('MVC FRAMEWORKS'),
       ('MVC PATTERN'),
       ('MVP'),
       ('MVVM'),
       ('MYSQL'),
       ('NAGIOS'),
       ('NEST.JS'),
       ('NESTJS'),
       ('NETWORK'),
       ('NETWORK ADMINISTRATION'),
       ('NETWORK PROTOCOLS'),
       ('NETWORKING'),
       ('NETWORKS'),
       ('NEXT.JS'),
       ('NGINX'),
       ('NGNIX'),
       ('NGRX'),
       ('NHIBERNATE'),
       ('NIEMIECKI'),
       ('NLP'),
       ('NODE'),
       ('NODE.JS'),
       ('NODE.JS EXPRESS'),
       ('NODEJS'),
       ('NOSQL'),
       ('NPM'),
       ('NUMPY'),
       ('NUNIT'),
       ('OBJECTIVE-C'),
       ('OCTOPUS'),
       ('OFFICE 365'),
       ('OFFLINE STORAGE'),
       ('OLAP'),
       ('OOD'),
       ('OOP'),
       ('OPEN SOURCE'),
       ('OPENCV'),
       ('OPENGL'),
       ('OPENSHIFT'),
       ('OPENSTACK'),
       ('ORACLE'),
       ('ORACLE DB'),
       ('ORACLE SQL'),
       ('ORACLE WEBLOGIC'),
       ('ORM'),
       ('OS X LINUX'),
       ('OWASP'),
       ('PANDAS'),
       ('PENTAHO'),
       ('PEOPLE MANAGEMENT'),
       ('PERL'),
       ('PHOTOSHOP'),
       ('PHP'),
       ('PHP 5'),
       ('PHP 5.4'),
       ('PHP 7'),
       ('PHP 7.X'),
       ('PHP 8'),
       ('PHPUNIT'),
       ('PL/SQL'),
       ('PLAYWRIGHT'),
       ('PM'),
       ('POLISH'),
       ('POSTGRESQL'),
       ('POSTMAN'),
       ('POSTRESQL'),
       ('POWER BI'),
       ('POWERSHELL'),
       ('PRESTASHOP'),
       ('PRINCE2'),
       ('PROACTIVITY'),
       ('PROBLEM SOLVING'),
       ('PRODUCT MANAGEMENT'),
       ('PROGRAMMING'),
       ('PROJECT MANAGEMENT'),
       ('PROMETHEUS'),
       ('PROTOTYPING'),
       ('PROTRACTOR'),
       ('PUPPET'),
       ('PUSH NOTIFICATIONS'),
       ('PWA'),
       ('PYQT'),
       ('PYSPARK'),
       ('PYTEST'),
       ('PYTHON'),
       ('PYTHON 3'),
       ('PYTHON 3.X'),
       ('PYTORCH'),
       ('QA'),
       ('QT'),
       ('QUALITY ASSURANCE'),
       ('R'),
       ('RABBITMQ'),
       ('RAILS'),
       ('RAZOR'),
       ('RDBMS'),
       ('REACT'),
       ('REACT NATIVE'),
       ('REACTIVE PROGRAMMING'),
       ('REACTJS'),
       ('REALM'),
       ('REASON'),
       ('RED HAT'),
       ('REDIS'),
       ('REDMINE'),
       ('REDUX'),
       ('RELACYJNE BAZY DANYCH'),
       ('RELATIONAL DATABASES'),
       ('RESPONSIVE WEB DESIGN'),
       ('REST'),
       ('REST API'),
       ('REST SERVICES'),
       ('RESTFUL'),
       ('RESTFUL API'),
       ('RETROFIT'),
       ('RISK MANAGEMENT'),
       ('ROBOT FRAMEWORK'),
       ('ROUTING'),
       ('RPA'),
       ('RPG'),
       ('RSPEC'),
       ('RTOS'),
       ('RUBY'),
       ('RUBY ON RAILS'),
       ('RUST'),
       ('RWD'),
       ('RXJAVA'),
       ('RXJAVA 2'),
       ('RXJS'),
       ('RXKOTLIN'),
       ('RXSWIFT'),
       ('SAAS'),
       ('SALES'),
       ('SALESFORCE'),
       ('SAP'),
       ('SAP BO'),
       ('SAP HANA'),
       ('SAP MM'),
       ('SAP SD'),
       ('SAS'),
       ('SASS'),
       ('SASS (BEM)'),
       ('SCALA'),
       ('SCRAPY'),
       ('SCRIPTING'),
       ('SCRUM'),
       ('SCRUM MASTER'),
       ('SCSS'),
       ('SDLC'),
       ('SECURITY'),
       ('SELENIUM'),
       ('SELENIUM WEBDRIVER'),
       ('SEO'),
       ('SERVERLESS'),
       ('SERVICENOW'),
       ('SHAREPOINT'),
       ('SHELL'),
       ('SHELL SCRIPTING'),
       ('SHOPIFY'),
       ('SIEM'),
       ('SIP'),
       ('SKETCH'),
       ('SLACK'),
       ('SNOWFLAKE'),
       ('SOA'),
       ('SOAP'),
       ('SOAPUI'),
       ('SOCIAL MEDIA'),
       ('SOCKET.IO'),
       ('SOFTWARE ARCHITECTURE'),
       ('SOFTWARE DEVELOPMENT'),
       ('SOLID'),
       ('SOLID PRINCIPLES'),
       ('SOLIDITY'),
       ('SOLR'),
       ('SONAR'),
       ('SONARQUBE'),
       ('SPA'),
       ('SPARK'),
       ('SPLUNK'),
       ('SPOCK'),
       ('SPRING'),
       ('SPRING 5'),
       ('SPRING BOOT'),
       ('SPRING CLOUD'),
       ('SPRING MVC'),
       ('SQL'),
       ('SQL SERVER'),
       ('SQLALCHEMY'),
       ('SQLITE'),
       ('SSAS'),
       ('SSIS'),
       ('SSRS'),
       ('STATISTICS'),
       ('STL'),
       ('SVG'),
       ('SVN'),
       ('SWAGGER'),
       ('SWIFT'),
       ('SWIFTUI'),
       ('SWING'),
       ('SYMFONY'),
       ('SYMFONY 2'),
       ('SYMFONY 3'),
       ('SYMFONY 4'),
       ('SYMPHONY'),
       ('T-SQL'),
       ('TABLEAU'),
       ('TABULAR'),
       ('TCP'),
       ('TCP/IP'),
       ('TDD'),
       ('TEAM LEADERSHIP'),
       ('TEAM MANAGEMENT'),
       ('TEAM PLAYER'),
       ('TEAMCITY'),
       ('TEAMWORK'),
       ('TELCO'),
       ('TENSORFLOW'),
       ('TERADATA'),
       ('TERRAFORM'),
       ('TEST AUTOMATION'),
       ('TEST CASES'),
       ('TEST PLANNING'),
       ('TEST SCENARIOS'),
       ('TESTING'),
       ('TESTING MOBILE APPS'),
       ('TESTING TOOLS'),
       ('TESTLINK'),
       ('TESTRAIL'),
       ('TESTY FUNKCJONALNE'),
       ('TFS'),
       ('TOGAF'),
       ('TOMCAT'),
       ('TORNADO'),
       ('TROUBLESHOOTING'),
       ('TWIG'),
       ('TYPESCRIPT'),
       ('UBUNTU'),
       ('UI'),
       ('UI DESIGN'),
       ('UIKIT'),
       ('UIPATH'),
       ('UML'),
       ('UNIT TESTING'),
       ('UNITY'),
       ('UNITY 3D'),
       ('UNIX'),
       ('UNREAL ENGINE'),
       ('UNREAL ENGINE 4'),
       ('USABILITY TESTING'),
       ('USER INTERFACE'),
       ('USER STORIES'),
       ('UX'),
       ('UX DESIGN'),
       ('UX RESEARCH'),
       ('UX/UI'),
       ('UXPIN'),
       ('VAADIN'),
       ('VAGRANT'),
       ('VARNISH'),
       ('VB.NET'),
       ('VBA'),
       ('VIRTUALIZATION'),
       ('VISUAL BASIC'),
       ('VISUAL STUDIO'),
       ('VMWARE'),
       ('VOIP'),
       ('VPN'),
       ('VUE'),
       ('VUE.JS'),
       ('WCF'),
       ('WEB API'),
       ('WEB APPLICATION TESTING'),
       ('WEB APPLICATIONS'),
       ('WEB DEVELOPMENT'),
       ('WEB SERVICES'),
       ('WEBCON'),
       ('WEBCON BPS'),
       ('WEBDRIVER'),
       ('WEBGL'),
       ('WEBLOGIC'),
       ('WEBMETHODS'),
       ('WEBPACK'),
       ('WEBSERVICE'),
       ('WEBSOCKET'),
       ('WEBSPHERE'),
       ('WILDFLY'),
       ('WINDOWS'),
       ('WINDOWS 10'),
       ('WINDOWS ADMINISTRATION'),
       ('WINDOWS FORMS'),
       ('WINDOWS SERVER'),
       ('WINFORMS'),
       ('WOOCOMMERCE'),
       ('WORDPRESS'),
       ('WPF'),
       ('WRITING TEST CASES'),
       ('WRITING TEST SCENARIOS'),
       ('XAMARIN'),
       ('XCODE'),
       ('XML'),
       ('XPATH'),
       ('XSD'),
       ('XSLT'),
       ('YARN'),
       ('YII'),
       ('ZABBIX'),
       ('ZEND'),
       ('ZEND EXPRESSIVE'),
       ('ZEND FRAMEWORK'),
       ('ZEPLIN'),
       ('ZMQ');

create table if not exists required_skill
(
    id           serial primary key                         not null,
    level        int check ( (level <= 5) and (level >= 1)) not null,
    job_offer_id int,
    skill_id     int                                        not null,
    constraint fk_job_offer foreign key (job_offer_id) references job_offer (id),
    constraint fk_skill foreign key (skill_id) references skill (id)
);

create table if not exists message_queue
(
    id           serial primary key                                          not null,
    title        varchar(100) check (length(title) between 1 and 100)        not null,
    location     varchar(100) check (length(location) between 1 and 200)     not null,
    recipient    varchar(100) check (length(recipient) between 1 and 100)    not null,
    created_date timestamp(6)                                                not null,
    contact_name varchar(100) check (length(contact_name) between 1 and 100) not null,
    send         boolean                                                     not null
);