openapi: 3.0.3
info:
  title: Job offer Service
  version: 1.0.1
tags:
  - name: Basic
    description: Basic CRUD operations on Job offers
components:
  schemas:
    JobOffer:
      type: object
      properties:
        title:
          type: string
        companyName:
          type: string
        city:
          type: string
        street:
          type: string
        description:
          type: string
        remoteInterview:
          type: boolean
        experienceLevel:
          $ref: '#/components/schemas/ExperienceLevel'
        mainTechnology:
          type: string
        typeOfWork:
          $ref: '#/components/schemas/TypeOfWork'
        employments:
          type: array
          items:
            $ref: '#/components/schemas/Employment'
        operatingModes:
          type: array
          items:
            $ref: '#/components/schemas/OperatingMode'
          minItems: 1
          maxItems: 3
        requiredSkills:
          type: array
          items:
            $ref: '#/components/schemas/RequiredSkill'
          maxItems: 10
          minItems: 1
        applyUrl:
          type: string
        contactEmail:
          type: string
        contactName:
          type: string
        contactPhone:
          type: string

      required:
        - title
        - companyName
        - city
        - street
        - typeOfWork
        - description
        - operatingModes
        - employments
        - contactName
        - contactEmail
        - requiredSkills
        - experienceLevel
        - mainTechnology

    Employment:
      type: object
      properties:
        type:
          type: string
          enum:
            - b2b
            - permanent
            - mandate
            - specific_task
            - internship
        from:
          type: integer
        to:
          type: integer
        currency:
          $ref: '#/components/schemas/Currency'
      required:
        - type
        - currency
    RequiredSkill:
      type: object
      properties:
        name:
          type: string
          enum:
            - js
            - html
            - php
            - ruby
            - python
            - java
            - .net
            - scala
            - c
            - mobile
            - testing
            - devops
            - admin
            - uxui
            - pm
            - game
            - analytics
            - security
            - data
            - go
            - support
            - erp
            - architecture
        level:
          type: integer
          minimum: 1
          maximum: 5
      required:
        - name
        - level
    OperatingMode:
      type: string
      enum:
        - remote
        - hybrid
        - office
    ExperienceLevel:
      type: string
      enum:
        - junior
        - mid
        - senior
        - lead
    TypeOfWork:
      type: string
      enum:
        - full_time
        - part_time
        - internship
        - freelance
    Currency:
      type: string
      enum:
        - pln
        - eur
        - usd
        - gbp
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
          enum:
            - MISSING_CONTENT
            - OFFER_NOT_FOUND
            - MISSING_COMPANY_NAME
      required:
        - message
        - code
    JobOfferMetadata:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    FetchedJobOffer:
      type: object
      properties:
        title:
          type: string
        companyName:
          type: string
        city:
          type: string
        street:
          type: string
        description:
          type: string
        remoteInterview:
          type: boolean
        experienceLevel:
          $ref: '#/components/schemas/ExperienceLevel'
        mainTechnology:
          type: string
        typeOfWork:
          $ref: '#/components/schemas/TypeOfWork'
        employments:
          type: array
          items:
            $ref: '#/components/schemas/Employment'
        operatingModes:
          type: array
          items:
            $ref: '#/components/schemas/OperatingMode'
          minItems: 1
          maxItems: 3
        requiredSkills:
          type: array
          items:
            $ref: '#/components/schemas/RequiredSkill'
          maxItems: 10
          minItems: 1
      required:
        - title
        - companyName
        - city
        - street
        - typeOfWork
        - description
        - operatingModes
        - employments
        - requiredSkills
        - experienceLevel
        - mainTechnology
  examples:
    MaximalJobOffer:
      value:
        title: "Senior Java developer needed asap"
        companyName: "Some company name"
        city: "Some city"
        street: "Some street"
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit
        remoteInterview: true
        experienceLevel: senior
        mainTechnology: java
        typeOfWork: full_time
        employments:
          - type: b2b
            from: 130000
            to: 15000
            currency: pln
          - type: permanent
            from: 100000
            to: 13000
            currency: pln
        operatingModes:
          - remote
          - hybrid
          - office
        requiredSkills:
          - name: java
            level: 5
        applyUrl: http://example.com
        contactName: John Doe
        contactEmail: contac@email.com
        contactPhone: "48123321123"
    MinimalJobOffer:
      value:
        title: "Senior Java developer needed asap"
        companyName: "Some company name"
        city: "Some city"
        street: "Some street"
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit
        experienceLevel: senior
        mainTechnology: java
        typeOfWork: part_time
        employments:
          - type: permanent
            currency: pln
        operatingModes:
          - office
        requiredSkills:
          - name: java
            level: 5
        contactName: John Doe
        contactEmail: contac@email.com
        contactPhone: "48123321123"
  parameters:
    query-param-type-of-work:
      name: type-of-work
      description: Work type filter
      in: query
      required: false
      schema:
        type: string
        enum:
          - full_time
          - part_time
          - internship
          - freelance
    query-param-job-offer-employment-type:
      name: employment-type
      description: Employment type filter
      in: query
      required: false
      schema:
        type: string
        enum:
          - b2b
          - permanent
          - internship
          - mandate
          - specific_task
    query-param-job-offer-main-skill:
      name: skill
      description: Main skill filter
      in: query
      required: false
      schema:
        type: string
    query-param-job-offer-experience:
      name: experience
      description: Experience filter
      in: query
      required: false
      schema:
        type: string
        enum:
          - junior
          - mid
          - senior
          - lead
    query-param-operating-mode:
      name: operating-mode
      description: Operating mode filter
      in: query
      required: false
      schema:
        type: string
        enum:
          - remote
          - hybrid
          - office
    query-param-salary-min:
      name: salary-min
      description: Minimal salary filter
      in: query
      required: false
      schema:
        type: integer
    query-param-salary-max:
      name: salary-max
      description: Maximal salary filter
      in: query
      required: false
      schema:
        type: integer
    path-param-job-offer-id:
      name: id
      description: Job offer id
      in: path
      required: true
      schema:
        type: integer

paths:
  /job-offers:
    get:
      operationId: findJobOffers
      parameters:
        - $ref: '#/components/parameters/query-param-salary-min'
        - $ref: '#/components/parameters/query-param-salary-max'
        - $ref: '#/components/parameters/query-param-job-offer-main-skill'
        - $ref: '#/components/parameters/query-param-job-offer-employment-type'
        - $ref: '#/components/parameters/query-param-job-offer-experience'
        - $ref: '#/components/parameters/query-param-operating-mode'
        - $ref: '#/components/parameters/query-param-type-of-work'
      summary: Searches for job offers by parameter and returns an Array
      tags:
        - Basic
      responses:
        '200':
          description: Array of found job offers
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FetchedJobOffer'
              examples:
                MaxJobOffer:
                  $ref: '#/components/examples/MaximalJobOffer'
                MinimalJobOffer:
                  $ref: '#/components/examples/MinimalJobOffer'
  /job-offer:
    post:
      operationId: createJobOffer
      tags:
        - Basic
      summary: Creates a new job offer
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/JobOffer'
            examples:
              MaximalJobOffer:
                $ref: '#/components/examples/MaximalJobOffer'
              MinimalJobOffer:
                $ref: '#/components/examples/MinimalJobOffer'
      responses:
        '201':
          description: Job offer was created with following ID
          headers:
            location:
              schema:
                type: string
              description: URL of created job offer
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/JobOfferMetadata'
              example:
                id: "1020x20"
        '400':
          description: There was a problem with a request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
  /job-offer/{id}:
    delete:
      operationId: deleteJobOffer
      summary: Deletes a job offer
      tags:
        - Basic
      parameters:
        - $ref: '#/components/parameters/path-param-job-offer-id'
      responses:
        '200':
          description: Job offer has been deleted
        '404':
          description: Job offer does not exist
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateJobOffer
      summary: Updates an job offer
      tags:
        - Basic
      parameters:
        - $ref: '#/components/parameters/path-param-job-offer-id'
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/JobOffer'
            examples:
              MaximalJobOffer:
                $ref: '#/components/examples/MaximalJobOffer'
              MinimalJobOffer:
                $ref: '#/components/examples/MinimalJobOffer'
      responses:
        '200':
          description: Job offer has been updated
        '404':
          description: Job offer does not exist
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'
    get:
      operationId: findJobOffer
      summary: Returns an job offer
      tags:
        - Basic
      parameters:
        - $ref: '#/components/parameters/path-param-job-offer-id'
      responses:
        '200':
          description: Job offer has been found and returned
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/JobOffer'
        '404':
          description: Job offer does not exist
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Error'